name: MarstACK
version: v0.2.2-alpha2
slug: marstack
description: Keep your Marstek battery operational without cloud access
url: https://github.com/fignew/MarstACK
icon: icon.png
arch:
  - amd64
  - aarch64
  - armv7
startup: application
boot: auto
ports:
  8000/tcp: null
ingress: false
host_network: false
image: ghcr.io/hoferbeck/marstack
options:
  log_level: info
schema:
  log_level: list(error|info|debug)
