name: MarstACK
version: v0.3.0
slug: marstack
description: Keep your Marstek battery operational without cloud access
url: https://github.com/hoferbeck/MarstACK
icon: icon.png
arch:
  - amd64
  - aarch64
startup: application
boot: auto
ports:
  8000/tcp: null
ingress: false
host_network: false
image: ghcr.io/hoferbeck/marstack
options:
  log_level: info
  FORWARDED_ALLOW_IPS: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
  APP_TIMEZONE: Europe/Berlin
schema:
  log_level: list(error|info|debug)
  FORWARDED_ALLOW_IPS: str
  APP_TIMEZONE: str